# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Hexagon\Presentation\Controller\:
        resource: '../src/Hexagon/Presentation/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    meeting.notifier:
        class: App\Hexagon\Domain\Component\MeetingNotifier
    report.notifier:
        class: App\Hexagon\Domain\Component\ReportNotifier

    App\Hexagon\Presentation\Controller\MeetingController:
        class: App\Hexagon\Presentation\Controller\MeetingController
        arguments: ['@meeting.notifier']

    App\Hexagon\Presentation\Controller\ReportController:
        class: App\Hexagon\Presentation\Controller\ReportController
        arguments: ['@report.notifier']